-- AlterTable
ALTER TABLE "DeadlineExtensions" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "EditLogs" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "EditType" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
